name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
  github-token:
    required: true
    description: 'github token'
    default: ${{ github.token }}
  required-input:
    required: true
    description: ''
    default: '  '
runs:
  using: 'node12'
  main: 'dist/index.js'
